# Generated by Django 6.0.3 on 2026-04-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='title',
        ),
    ]
